%YAML 1.1
---
# workspace: '/path/to/ws'
# environment: null
# plugin_blacklist: []
# cpp:
#    parser_lib: '/usr/lib/llvm-3.8/lib'
#    std_includes: '/usr/lib/llvm-3.8/lib/clang/3.8.0/include'
#    compile_db: '/path/to/ws/build'
# analysis:
#    ignore:
#        tags: []
#        rules: []
#        metrics: []
